### ISSUE TITLE
Error while build on linux ubuntu

### ISSUE THREAD

**Issue by Shamber** [sagi-z/BackgroundSubtractorCNT#3]
Hello. I download and compile as describe in readme.
But  output of cmake 
 `
cmake -DBUILD_TEST=ON -DBUILD_SHARED_LIBS=ON -DPYTHON_EXTENSION=ON -DCMAKE_BUILD_TYPE=RELEASE ..
OpenCV_LIBS_NATIVE is: 'opencv_calib3d','opencv_core','opencv_features2d','opencv_flann','opencv_highgui','opencv_imgcodecs','opencv_imgproc','opencv_ml','opencv_objdetect','opencv_photo','opencv_shape','opencv_stitching','opencv_superres','opencv_video','opencv_videoio','opencv_videostab','opencv_aruco','opencv_bgsegm','opencv_bioinspired','opencv_ccalib','opencv_datasets','opencv_dnn','opencv_dpm','opencv_face','opencv_freetype','opencv_fuzzy','opencv_line_descriptor','opencv_optflow','opencv_phase_unwrapping','opencv_plot','opencv_reg','opencv_rgbd','opencv_saliency','opencv_stereo','opencv_structured_light','opencv_surface_matching','opencv_text','opencv_tracking','opencv_xfeatures2d','opencv_ximgproc','opencv_xobjdetect','opencv_xphoto'
OpenCV_LIB_DIR_NATIVE is: 
OpenCV_INCLUDE_DIRS_NATIVE is: '/usr/local/include','/usr/local/include/opencv'
CMAKE_CURRENT_SOURCE_DIR_NATIVE is: /home/docker/BackgroundSubtractorCNT/python
BGSUBCNT_INCLUDE_DIR_NATIVE is: /home/docker/BackgroundSubtractorCNT
PYTHON_PREFIX is /usr
PYTHON_SITE_DIR is lib/python2.7/dist-packages
-- Configuring done
-- Generating done
-- Build files have been written to: /home/docker/BackgroundSubtractorCNT/build
`

and after when i use python  i have error : 
`Traceback (most recent call last):
  File "/home/docker/peoplecnt.py", line 3, in <module>
    import bgsubcnt                               # 1. New import
  File "/usr/local/lib/python2.7/dist-packages/bgsubcnt.py", line 28, in <module>
    _bgsubcnt = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/bgsubcnt.py", line 24, in swig_import_helper
    _mod = imp.load_module('_bgsubcnt', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/_bgsubcnt.so: undefined symbol: _ZTIN2cv12MatAllocatorE`
and i can't use it can you help me.

**Comment by benoitrosa** [comment]
Same error here on ubuntu 16.04

**Comment by sagi-z** [comment]
I'm not getting this... just verified now.
What is the output of 'ldd /usr/local/lib/python2.7/dist-packages/_bgsubcnt.so'?

**Comment by benoitrosa** [comment]
Just reconfirming that it has the bug here. The C++ demo version is working well, and compilation/installation (using the deb) is fine, but importing the python module raises the abovementioned error. 

The output of 'ldd /usr/local/lib/python2.7/dist-packages/_bgsubcnt.so' is here : https://pastebin.com/UK7waRVt

**Comment by sagi-z** [comment]
I think I see the problem.
This library is targeted at OpenCV 3.1.0 and above and I see your build is trying to use OpenCV2.4

**Comment by benoitrosa** [comment]
Actually, I have both versions installed, it's probably picking up the wrong one. I'll try again by setting the OPENCV_DIR variable. 

A fix could be to set a minimum required OpenCV version in the CMakeLists

**Comment by sagi-z** [comment]
I was sure the syntax I used specifies a minimum...
I don't have another version installed, but I committed & pushed a more specific version range check to the 'python' branch.
If you take this branch you can see if it detects a wrong version okay for you ... I'll test this myself when I have some time.
I'll leave this issue open for now.

**Comment by benoitrosa** [comment]
A quick test on the python branch shows that I'm building against OpenCV 3.2.0 (cmake outputs "Found OpenCV: /usr/local (found version "3.2.0")"), but when running the ldd command as before, I still see openCV 2.4.0. 

The issue might be related to my custom OpenCV build and how it is interfaced with python. I'll inquire when I get a bit more time

**Comment by sagi-z** [comment]
This seems like a runtime environment issue. Some suggestions:
1) 'ldconfig -p|grep opencv'
If you don't see your opencv 3.2.0 libs there then do 'sudo ldconfig' to update the lib cache and try again.
2) check if you have LD_LIBRARY_PATH defined in your environment since it affects dynamic library directory search order.

**Comment by benoitrosa** [comment]
No luck, everything seems in order (both openCV versions appear under ldconfig and the LD_LIBRARY_PATH env variable is set correctly), but it keeps picking the wrong lib version. Might also be related to the swig configuration ?

**Comment by sagi-z** [comment]
1. Please send the output of 'ldconfig -p|grep opencv'
2. Start with a new build directory, and use cmake again, but then instead of 'make' use 'make VERBOSE=1' and send me the output.

**Comment by sagi-z** [comment]
Please also send the LD_LIBRARY_PATH

**Comment by sagi-z** [comment]
@benoitrosa I'm going to close this issue soon as it seems like your own local runtime environment issue.

**Comment by benoitrosa** [comment]
Sorry, I completely forgot to look at this ...

If no one else had the issue, it is most probably related to a local runtime env issue indeed. Go ahead and close, I'll reopen if I find some time to look into it with a clean runtime environment.
